version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - public-volume:/usr/src/app/public
      - private-volume:/usr/src/app/db
  mongo:
    container_name: mongo
    image: mongo
    privileged: true
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
  public-volume:
  private-volume: