version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./data/app:/usr/src/app/data/app
  mongo:
    container_name: mongo
    image: mongo
    privileged: true
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db