version: "3.7"
services:
  graph_ql:
    container_name: graph_ql
    restart: always
    build: ./docker/graph_ql
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./data/app:/usr/src/app/data/app
  app:
    container_name: app
    restart: always
    build: ./docker/app
    ports:
      - "8080:8080"
    depends_on:
      - graph_ql
  mongo:
    container_name: mongo
    image: mongo
    privileged: true
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db