/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate user */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all collections */
        get: operations["listCollections"];
        put?: never;
        /** Create a new collection */
        post: operations["createCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a collection by ID */
        get: operations["getCollection"];
        /** Update a collection */
        put: operations["updateCollection"];
        post?: never;
        /** Delete a collection */
        delete: operations["deleteCollection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock an encrypted collection with passphrase */
        post: operations["unlockCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List media in a collection */
        get: operations["listCollectionMedia"];
        put?: never;
        /** Upload a media file to a collection */
        post: operations["uploadMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import media from an external source */
        post: operations["importMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get media details
         * @description When status is `processing`, includes optional `progress` (stage, overall_percent, optional time hints). Responses use `Cache-Control: private, no-store` while processing so clients see fresh progress.
         */
        get: operations["getMedia"];
        put?: never;
        post?: never;
        /** Delete a media file */
        delete: operations["deleteMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream media content */
        get: operations["streamMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get media thumbnail frame (JPEG) */
        get: operations["getMediaThumb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/ytdlp-cookies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check if yt-dlp cookie file is configured */
        get: operations["getYtdlpCookiesStatus"];
        /** Upload/overwrite yt-dlp cookie file content */
        put: operations["putYtdlpCookies"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            expiresIn: string;
        };
        UserInfo: {
            username: string;
        };
        HealthResponse: {
            status: string;
            /** Format: date-time */
            timestamp: string;
        };
        Collection: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            is_encrypted: boolean;
            /** @description Whether the collection is currently unlocked (always true for non-encrypted) */
            is_unlocked: boolean;
            cover_url?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CollectionCreate: {
            name: string;
            description?: string;
            /** @description If provided, the collection will be encrypted with this passphrase */
            passphrase?: string;
        };
        CollectionUpdate: {
            name?: string;
            description?: string;
        };
        UnlockRequest: {
            passphrase: string;
        };
        UnlockResponse: {
            success: boolean;
        };
        /** @description Normalized tags extracted from the uploaded file (ffprobe), before transcoding */
        MediaMetadata: {
            title?: string | null;
            artist?: string | null;
            album?: string | null;
            album_artist?: string | null;
            genre?: string | null;
            year?: string | null;
            track?: string | null;
            composer?: string | null;
            comment?: string | null;
            encoder?: string | null;
            creation_time?: string | null;
        };
        /** @description Live job progress while status is processing (in-memory on the backend) */
        MediaProcessingProgress: {
            /** @enum {string} */
            stage: "downloading" | "transcoding" | "thumbnails" | "encrypting" | "uploading_main" | "uploading_thumbs";
            overall_percent: number;
            /** @description Encoder timeline position during transcoding when known */
            current_sec?: number | null;
            /** @description Estimated source duration used for transcoding progress */
            total_sec?: number | null;
        };
        Media: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            collection_id: string;
            title: string;
            description?: string;
            /** @enum {string} */
            media_type: "video" | "audio";
            duration_sec?: number | null;
            /** Format: int64 */
            file_size_bytes?: number | null;
            profile: string;
            mime_type?: string | null;
            /** @enum {string} */
            status: "processing" | "ready" | "error";
            /** Format: date-time */
            created_at: string;
            /** @description Number of video preview frames (0 for audio or processing) */
            thumb_frame_count?: number;
            /** @description ID3 / container tags from the original upload when ffprobe could read them */
            metadata?: components["schemas"]["MediaMetadata"] | null;
            /** @description Only while status is processing; null if the server restarted mid-job */
            progress?: components["schemas"]["MediaProcessingProgress"] | null;
        };
        ImportRequest: {
            /** @description Import source plugin identifier */
            source: string;
            /** @description URL to import from */
            url: string;
            /** @description Optional title override (auto-detected if omitted) */
            title?: string;
            /**
             * @default mp3-192
             * @enum {string}
             */
            profile: "mp3-128" | "mp3-192" | "mp3-320" | "aac-256";
        };
        UploadResponse: {
            /** Format: uuid */
            id: string;
            status: string;
        };
        YtdlpCookiesStatus: {
            configured: boolean;
        };
        YtdlpCookiesUpdate: {
            /** @description Netscape cookie file content for yt-dlp */
            cookies: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Missing credentials */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCollections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of collections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"][];
                };
            };
        };
    };
    createCollection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Collection created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
        };
    };
    getCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
            /** @description Collection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionUpdate"];
            };
        };
        responses: {
            /** @description Collection updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
        };
    };
    deleteCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unlockCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnlockRequest"];
            };
        };
        responses: {
            /** @description Collection unlocked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnlockResponse"];
                };
            };
            /** @description Wrong passphrase */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCollectionMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"][];
                };
            };
        };
    };
    uploadMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    title?: string;
                    description?: string;
                    /**
                     * @default 720p
                     * @enum {string}
                     */
                    profile?: "480p" | "720p" | "1080p" | "1080p60" | "mp3-128" | "mp3-192" | "mp3-320" | "aac-256";
                };
            };
        };
        responses: {
            /** @description Upload accepted, processing started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Collection is locked */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    importMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Import accepted, downloading and processing started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Collection is locked */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description Media not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/mp4": string;
                    "audio/mpeg": string;
                };
            };
            /** @description Partial content (range request) */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMediaThumb: {
        parameters: {
            query?: {
                /** @description Frame index from 0 (multiple frames for video hover preview) */
                i?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thumbnail image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
        };
    };
    getYtdlpCookiesStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cookie configuration status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YtdlpCookiesStatus"];
                };
            };
        };
    };
    putYtdlpCookies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YtdlpCookiesUpdate"];
            };
        };
        responses: {
            /** @description Cookie file updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YtdlpCookiesStatus"];
                };
            };
        };
    };
}
